### ISSUE TITLE
I have a problem with such an error when I execute the python projects/SGT/train_net.py --config-file projects/SGT/configs/MOT17/sgt_dla34.yaml --data-dir /root/datasets --num-gpus 2 OUTPUT_DIR /root/sgt_output/mot17_val/dla34_mot17-CHcommand

### ISSUE THREAD

**Issue by liuqigui** [HYUNJS/SGT#11]
Traceback (most recent call last):
  File "projects/SGT/train_net.py", line 70, in <module>
    launch(
  File "/home1/liuqigui/project/SGT-main/detectron2/detectron2/engine/launch.py", line 69, in launch
    mp.start_processes(
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home1/liuqigui/project/SGT-main/detectron2/detectron2/engine/launch.py", line 123, in _distributed_worker
    main_func(*args)
  File "/home1/liuqigui/project/SGT-main/projects/SGT/train_net.py", line 63, in main
    trainer = Trainer(cfg)
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/SGT/sgt/trainer.py", line 40, in __init__
    super().__init__(cfg)
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/EpochTrainer/epoch_trainer/default_epoch_trainer.py", line 52, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/SGT/sgt/trainer.py", line 68, in build_train_loader
    return build_mix_train_loader(cfg, mapper=mapper)
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/Datasets/MIX/build.py", line 115, in build_mix_train_loader
    dataset_dicts, required_meta_data = get_mix_dataset_dicts(cfg.DATASETS.TRAIN,
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/Datasets/MIX/build.py", line 88, in get_mix_dataset_dicts
    dataset_dicts, obj_id_set, bbox_stat = DatasetCatalog.get(dataset_name)
  File "/home1/liuqigui/project/SGT-main/detectron2/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/Datasets/MIX/builtin.py", line 160, in <lambda>
    DatasetCatalog.register(reg_dataset_name, lambda: load_mix_dataset_dicts(dataset_name, split, root_dir, fill_id_flag,
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/Datasets/MIX/builtin.py", line 275, in load_mix_dataset_dicts
    ratio_bbox_below_vis_per_seq = {
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/Datasets/MIX/builtin.py", line 276, in <dictcomp>
    k: 100 * num_bbox_below_vis_per_seq[k] / (num_bbox_below_vis_per_seq[k] + sum_bbox_per_seq[k]) for k in
ZeroDivisionError: division by zero

**Comment by HYUNJS** [comment]
It seems that you faced the same situation handled in https://github.com/HYUNJS/SGT/issues/9

**Comment by liuqigui** [comment]
Thanks for your reply, I've fixed the issue. However, I encountered a new problem. cuda=10.2，torch=1.11.0

Traceback (most recent call last):
  File "projects/SGT/train_net.py", line 70, in <module>
    launch(
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/home1/liuqigui/project/SGT-main/projects/SGT/train_net.py", line 65, in main
    return trainer.train()
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/EpochTrainer/epoch_trainer/default_epoch_trainer.py", line 198, in train
    self.train_epoch(start_iter, end_iter, epoch)
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/EpochTrainer/epoch_trainer/default_epoch_trainer.py", line 220, in train_epoch
    self.run_step()
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/SGT/sgt/trainer.py", line 158, in run_step
    loss_dict = self.model(data)
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/SGT/sgt/meta_arch/sgt.py", line 52, in forward
    trk_loss_dict = self.tracker(detector_outs, batched_inputs=batched_inputs)
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/SGT/sgt/meta_arch/graphtracker.py", line 143, in forward
    loss_dict = self.compute_loss(new_t1_feats_list, new_t2_feats_list, t1_info, t2_info, gt_ids_t2, edge_dicts)
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/SGT/sgt/meta_arch/graphtracker.py", line 74, in compute_loss
    node_cls_loss_t2 = self.node_cls_head(new_t2_feats_list, gt_ids_t2)
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/SGT/sgt/meta_arch/graph_heads.py", line 173, in forward
    node_cls_loss = self.node_cls_loss(pred_logits, gt_labels)
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home1/liuqigui/project/SGT-main/projects/SGT/../../projects/SGT/sgt/meta_arch/loss.py", line 62, in forward
    node_cls_loss = sigmoid_focal_loss_jit(
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: CUDA driver error: a PTX JIT compilation failed
