### ISSUE TITLE
KeyError: 'Non-existent config key: SGT'

### ISSUE THREAD

**Issue by liuqigui** [HYUNJS/SGT#12]
Hello, when I execute python projects/SGT/train_net.py --config-file projects/SGT/configs/MOT17/sgt_dla34.yaml --data-dir /root/datasets --num-gpus 1 -- eval-only OUTPUT_DIR /root/sgt_output/mot17_test/dla34_mot17-CH command, I encountered KeyError: 'Non-existent config key: SGT'. What should I do to fix it?
thank you!

**Comment by liuqigui** [comment]
/project/SGT-main$ python projects/SGT/train_net.py --config-file projects/SGT/configs/MOT17/sgt_dla34.yaml --data-dir /home1/liuqigui/project/dataset --num-gpus 1 --eval-only OUTPUT_DIR /home1/liuqigui/project/SGT-main/sgt_output/mot17_test/dla34_mot17-CH
Traceback (most recent call last):
  File "projects/SGT/train_net.py", line 70, in <module>
    launch(
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "projects/SGT/train_net.py", line 49, in main
    cfg = setup(args)
  File "projects/SGT/train_net.py", line 40, in setup
    cfg.merge_from_file(args.config_file)
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/detectron2/config/config.py", line 69, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/fvcore/common/config.py", line 123, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/wguo/anaconda3/envs/sgt1/lib/python3.8/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: SGT'
